Galileo-Galilei/kedro-mlflow

.github/workflows/dev.yml
.github/workflows/release.yml
.readthedocs.yml

Fix typo for docs requirements

Feature documentation

---

CHANGELOG.md
kedro_mlflow/framework/hooks/pipeline_hook.py
tests/framework/hooks/test_pipeline_hook.py

#32 Log only passed arguments and options as tags in MLflow

---

CHANGELOG.md
kedro_mlflow/framework/hooks/pipeline_hook.py
tests/framework/hooks/test_pipeline_hook.py

This closes #50. @akruszewski I let you review?

Fix #50 - Enable _generate_kedro_command to accept None default values

---

.bumpversion.cfg
README.md
docs/source/02_hello_world_example/02_first_steps.md
docs/source/03_tutorial/00_migration_guide.md

Address issues in this comment: https://github.com/Galileo-Galilei/kedro-mlflow/issues/6#issuecomment-720158441
- Add contributors section at the end of README
- Add a badge "commit since last release"
- Add a "Disclaimer" section in README to warn about the develoment status and API breaking changes
- Add a migration guide between versions in the docs
- Update bumpversion.cfg to dynamically update badge and docs when a new release is set
- I certify that (a) this contribution is my original creation and / or (b) to the extent …

PARTIAL #6 - Update README and add migration guide

---

.pre-commit-config.yaml
CHANGELOG.md
docs/source/03_tutorial/06_version_models.md
kedro_mlflow/io/models/mlflow_abstract_model_dataset.py
kedro_mlflow/io/models/mlflow_model_saver_dataset.py
tests/io/models/test_mlflow_model_saver_dataset.py

FIX #116 - Pass filepath in MlflowAbstractModelDataSet through PurePosixPath in init

---

.github/workflows/test.yml
CHANGELOG.md
README.md
docs/source/01_introduction/01_introduction.md
docs/source/02_installation/01_installation.md
docs/source/02_installation/02_setup.md
docs/source/02_installation/03_migration_guide.md
docs/source/03_getting_started/01_example_project.md
docs/source/04_experimentation_tracking/02_version_parameters.md
docs/source/04_experimentation_tracking/03_version_datasets.md
docs/source/04_experimentation_tracking/04_version_models.md
mlc_config.json

Improve documentation by detecting faster broken links.
Update the CI "test" on push to add an action for checking for broken links.
- N/A Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, …

PARTIAL #6 - Add Markdown links checker to avoid broken links in documentation

---

.github/workflows/prepare-release.yml

Release 0.7.0

---

.github/workflows/prepare-release.yml
requirements.txt
setup.py
tests/conftest.py
tests/framework/hooks/test_pipeline_hook.py

Update tests which were broken in 0.17.2 to continue #144.
- Update tests
- Fix typo in release workfow

Feature/migrate to 0.17.2

---

.github/workflows/check-links.yml

The file was not commited with previous PR
Add workflow file

Add missing workflow for broken links detection

---

.github/workflows/test.yml
.pre-commit-config.yaml
CHANGELOG.md
setup.py

Close #245 #247 #252 #254 #255 #257
- Update pinned dependencies of test and dev
- Add ``blacken-docs`` to pre-commit
- Enforce ``isort`` and ``black`` in the CI 

:arrow_up: Update lint and test dependencies

---

CHANGELOG.md
kedro_mlflow/config/kedro_mlflow_config.py
kedro_mlflow/template/project/mlflow.yml
tests/config/test_get_mlflow_config.py
tests/config/test_kedro_mlflow_config.py
tests/conftest.py
tests/framework/hooks/test_pipeline_hook.py
tests/io/models/test_mlflow_model_logger_dataset.py

Set up the experiment globally when setting the configuration interactively (#256)

---

.github/workflows/test.yml
CHANGELOG.md
docs/source/04_experimentation_tracking/06_mlflow_ui.md
docs/source/05_pipeline_serving/03_cli_modelify.md
docs/source/05_pipeline_serving/04_hook_pipeline_ml.md
kedro_mlflow/framework/cli/cli.py
tests/framework/cli/test_cli.py

Implement #275
- modify UI command to check URI format

:sparkles: - Open the UI when the tracking uri begins with http (#275)

---

.pre-commit-config.yaml
CHANGELOG.md
kedro_mlflow/mlflow/kedro_pipeline_model.py
setup.py

Close #273
- Change defaut input dataset to ``MemoryDataSet``

Remove unnecessary dependency to input dataset in KedroPipelineModel 

---

.github/workflows/test.yml
CHANGELOG.md
README.md

Close #118
Document the fact that kedro-mlflow is now conda installable.

:sparkles: Release kedro-mlflow on conda-forge (#118)

---

setup.cfg

Fix bumpversion config to remove files which no longer refer to the version. This blocks the CI.

:green_heart: Reconfigure bumpversion to fix CI

---

CHANGELOG.md
docs/source/02_installation/03_migration_guide.md
docs/source/05_pipeline_serving/02_custom_kedro_pipeline_model.md
kedro_mlflow/config/kedro_mlflow_config.py
kedro_mlflow/extras/extensions/ipython.py
kedro_mlflow/framework/cli/cli.py
kedro_mlflow/framework/hooks/node_hook.py
kedro_mlflow/framework/hooks/pipeline_hook.py
kedro_mlflow/framework/hooks/utils.py
tests/config/test_get_mlflow_config.py
tests/config/test_kedro_mlflow_config.py
tests/conftest.py
tests/extras/extensions/test_ipython.py
tests/framework/cli/test_cli.py
tests/framework/cli/test_cli_modelify.py
tests/framework/hooks/test_all_hooks.py
tests/framework/hooks/test_node_hook.py
tests/framework/hooks/test_pipeline_hook.py

- Change ``KedroMlflowConfig.setup`` and ``get_mlflow_config`` so that they take ``context`` as an argument instead of ``session``
- Add ``after_context_created`` method in ``MlflowNodeHook`` and ``MlflowPipelineHook`` to setup mlflow configuration. 
- change ``_assert_mlflow_enabled`` function to take the mlflow configuration as input.
- Update test,documentation and ipython setup accordingly
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit …

Migrate to kedro==0.18.1

---

docs/source/05_pipeline_serving/01_mlflow_models.md

:memo: Fix typo in 01_mlflow_models.md

---

docs/source/06_interactive_use/01_notebook_use.md

Fix spelling in Readme

---

CHANGELOG.md
docs/source/04_experimentation_tracking/01_configuration.md

:memo: Update documentation about model registry with local relative filepath (#400)

---

CHANGELOG.md
kedro_mlflow/framework/cli/cli.py
tests/framework/cli/test_cli_modelify.py

Close #405
TODO: 
- add tests
- check run name 
- add command to egnerate the run as a tag

Enable using pip-requirements in modelify command

---

CHANGELOG.md

:memo: Fix changelog typo

---

.pre-commit-config.yaml
CHANGELOG.md
kedro_mlflow/framework/hooks/mlflow_hook.py
tests/config/test_get_mlflow_config.py
tests/framework/hooks/test_hook_pipeline_ml.py

Close #430 
Add a default ``mlflow`` entry in ``context.config_loader.config_patterns``.

Make kedro-mlflow compatible with OmegaConfigLoader

---

.github/workflows/test.yml
CHANGELOG.md
CONTRIBUTING.md
docs/source/04_experimentation_tracking/02_version_parameters.md
docs/source/05_framework_ml/03_framework_solutions.md
docs/source/05_pipeline_serving/02_custom_kedro_pipeline_model.md
docs/source/05_pipeline_serving/04_hook_pipeline_ml.md
docs/source/07_python_objects/01_DataSets.md
docs/source/07_python_objects/03_Pipelines.md
kedro_mlflow/framework/hooks/mlflow_hook.py
setup.py
tests/framework/hooks/test_hook_pipeline_ml.py
tests/io/models/test_mlflow_model_logger_dataset.py
tests/io/models/test_mlflow_model_saver_dataset.py
tests/mlflow/test_kedro_pipeline_model.py

:heavy_minus_sign: Drop support for python 3.7 (#391)

---

.pre-commit-config.yaml
kedro_mlflow/config/kedro_mlflow_config.py
kedro_mlflow/framework/cli/cli.py
kedro_mlflow/framework/hooks/utils.py
kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py
kedro_mlflow/io/models/mlflow_model_logger_dataset.py
kedro_mlflow/io/models/mlflow_model_saver_dataset.py
kedro_mlflow/mlflow/kedro_pipeline_model.py
kedro_mlflow/pipeline/pipeline_ml.py
setup.py
tests/config/test_kedro_mlflow_config.py
tests/framework/cli/test_cli.py
tests/framework/cli/test_cli_modelify.py
tests/framework/hooks/test_hook_active_run.py
tests/framework/hooks/test_hook_deactivate_tracking.py
tests/framework/hooks/test_hook_log_metrics.py
tests/framework/hooks/test_hook_log_parameters.py
tests/framework/hooks/test_hook_on_pipeline_error.py
tests/framework/hooks/test_run_name.py
tests/io/artifacts/test_mlflow_artifact_dataset.py
tests/io/metrics/test_mlflow_metric_dataset.py
tests/io/models/test_mlflow_model_registry_dataset.py
tests/pipeline/test_pipeline_ml.py
tests/test_utils.py

Upgrade black
Change black dependecies and run ``black .`` and pre-commit with blacken-docs on the wholde codebase

:arrow_up: Upgrade black to 2023 major version

---

.readthedocs.yml
CHANGELOG.md
docs/source/03_getting_started/02_first_steps.md
docs/source/04_experimentation_tracking/02_version_parameters.md
docs/source/05_pipeline_serving/04_hook_pipeline_ml.md
kedro_mlflow/mlflow/kedro_pipeline_model.py
tests/config/test_get_mlflow_config.py
tests/framework/hooks/test_hook_deactivate_tracking.py
tests/framework/hooks/test_hook_log_metrics.py
tests/framework/hooks/test_hook_pipeline_ml.py
tests/io/artifacts/test_mlflow_artifact_dataset.py
tests/io/models/test_mlflow_model_logger_dataset.py
tests/io/models/test_mlflow_model_saver_dataset.py
tests/mlflow/test_kedro_pipeline_model.py

Part of #391
Update tests and documentation
- [] Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- I certify that the …

Remove TemplatedConfigloader in favor of OmegaConfigLoader

---

CHANGELOG.md
docs/source/01_introduction/02_motivation.md
docs/source/02_installation/03_migration_guide.md
docs/source/03_getting_started/02_first_steps.md
docs/source/04_experimentation_tracking/01_configuration.md
docs/source/04_experimentation_tracking/04_version_models.md
docs/source/05_framework_ml/03_framework_solutions.md
docs/source/05_pipeline_serving/04_hook_pipeline_ml.md
docs/source/07_python_objects/01_DataSets.md
docs/source/08_API/kedro_mlflow.io.rst
kedro_mlflow/io/models/__init__.py
kedro_mlflow/io/models/mlflow_model_local_filesystem_dataset.py
kedro_mlflow/io/models/mlflow_model_registry_dataset.py
kedro_mlflow/io/models/mlflow_model_tracking_dataset.py
setup.py
tests/framework/hooks/test_hook_deactivate_tracking.py
tests/framework/hooks/test_hook_pipeline_ml.py
tests/io/metrics/test_mlflow_metric_history_dataset.py
tests/io/models/test_mlflow_model_local_filesystem_dataset.py
tests/io/models/test_mlflow_model_tracking_dataset.py
tests/mlflow/test_kedro_pipeline_model.py

-  Rename ``MlflowModelLoggerDataSet`` to ``MlflowModelTrackingDataset`` and ``MlflowModelSaverDataSet`` to ``MlflowModelLocalFileSystemDataset``, and all the references in the code (including the filenames)
- Fix broken tests due to kedro-datasets dependencies and msot recent mlflow versions. 
- I certify that the use of this contribution as …

Rename Models Datasets

---

.github/workflows/test.yml
.pre-commit-config.yaml
kedro_mlflow/config/kedro_mlflow_config.py
kedro_mlflow/framework/cli/cli.py
kedro_mlflow/framework/hooks/__init__.py
kedro_mlflow/framework/hooks/mlflow_hook.py
kedro_mlflow/io/artifacts/__init__.py
kedro_mlflow/io/metrics/__init__.py
kedro_mlflow/io/metrics/mlflow_metric_dataset.py
kedro_mlflow/io/models/__init__.py
kedro_mlflow/io/models/mlflow_model_tracking_dataset.py
kedro_mlflow/mlflow/kedro_pipeline_model.py
kedro_mlflow/pipeline/__init__.py
kedro_mlflow/pipeline/pipeline_ml.py
kedro_mlflow/utils.py
pyproject.toml
setup.py
tests/framework/cli/test_cli_utils.py
tests/framework/hooks/test_hook_deactivate_tracking.py
tests/framework/hooks/test_hook_log_metrics.py
tests/framework/hooks/test_utils_flatten_dict.py
tests/io/metrics/test_mlflow_metric_dataset.py
tests/io/models/test_mlflow_model_tracking_dataset.py
tests/mlflow/test_kedro_pipeline_model.py
tests/template/project/test_mlflow_yml.py

Introduce ruff as a replacement for black, isort, flake8 and pylint(#470)

---

kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py
tests/config/test_get_mlflow_config.py
tests/conftest.py
tests/framework/cli/test_cli.py
tests/framework/cli/test_cli_modelify.py
tests/framework/hooks/test_hook_deactivate_tracking.py
tests/framework/hooks/test_hook_on_pipeline_error.py
tests/io/artifacts/test_mlflow_artifact_dataset.py

Fix tests on kedro "develop" branch and test behaviour with frozen context
- ``pytproject.toml`` has a new key kedro_init_version
- ``MLflowArtifactDataset`` continue parsing Class object instead of only string 
- project template is upadted to take int account kedro refactorng (tets outside of src...)
- Remove ``TemplatedConfigLoader`` and ``ConfigLoader`` everywhere
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original …

Test_frozen_context

---

.github/workflows/prepare-release.yml

:green_heart: Upgrade actions versions and migrate from bump2version to bump-my-version

---

setup.py

Close #490 #492 #517 #518
Upgrade dependencies 

:arrow_up: Upgrade ruff, sphinx_rtd_theme, sphinx-click and scikit-learn

---

setup.py
tests/config/test_get_mlflow_config.py
tests/conftest.py
tests/framework/cli/test_cli_modelify.py
tests/framework/hooks/test_hook_pipeline_ml.py

Many tests were failing after kedro 0.19.2 release
Update pyproject.toml to match new kedro format

:white_check_mark: Upgrade pyproject.toml to make tests pass in kedro==0.19.2

---

CHANGELOG.md
docs/source/04_experimentation_tracking/01_configuration.md
kedro_mlflow/config/resolvers.py
kedro_mlflow/framework/hooks/mlflow_hook.py
kedro_mlflow/template/project/mlflow.yml
tests/config/test_resolvers.py

Add a km.random_name resolver to enable auto-generated names in configuration

---

CHANGELOG.md
docs/source/04_experimentation_tracking/01_configuration.md

Close #395
Update doc to add reference to runtime_params resolver and examples

Document the ability to update configuration at runtime (#395)

---

CHANGELOG.md

:memo: Fix typo in CHANGELOG.md

---

.github/workflows/test.yml
.pre-commit-config.yaml
kedro_mlflow/__init__.py
kedro_mlflow/config/kedro_mlflow_config.py
kedro_mlflow/framework/__init__.py
pyproject.toml
setup.py
tests/framework/cli/test_cli_modelify.py

Close #492 #524 #527 #532 #543 #547 #572

:arrow_up: :rotating_light: :white_check_mark:  Upgrade dependencies bound, ruff configuration and linting and mlflow tests

---

CHANGELOG.md
docs/source/05_framework_ml/01_why_framework.md
docs/source/05_pipeline_serving/01_mlflow_models.md
docs/source/07_python_objects/03_Pipelines.md
kedro_mlflow/framework/hooks/mlflow_hook.py
kedro_mlflow/io/models/mlflow_model_tracking_dataset.py
tests/io/models/test_mlflow_model_tracking_dataset.py

:loud_sound: Use MlflowHook internal logger and log the active run (#567)

---

pyproject.toml

Fix workflow  https://github.com/Galileo-Galilei/kedro-mlflow/actions/runs/13020749238/job/36320633246

:construction_worker: Fix reference for bumpversion

---

docs/index.md

This PR added a video covering a detailed usage of Kedro-MLflow plugin. A couple of typos are fixed as well
I have changed the documentation file and built it locally using `sphinx-build`

added a video to the resources, fixed typos
