CHANGELOG.md, kedro_mlflow/framework/hooks/pipeline_hook.py, tests/framework/hooks/test_pipeline_hook.py
This closes #10 but the tests currently fail: we need #51  to be merged first, and then rebase on develop.
=> FIX #10 - Close mlflow runs with  on pipeline error 

CHANGELOG.md, docs/source/01_introduction/02_motivation.md, docs/source/02_hello_world_example/01_example_project.md
Fix #34, #35, #36 documentation error spotted by @lawwu. This PR respects the guidelines.
=> Documentation typo

CHANGELOG.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/pipeline/modular_pipeline_ml.py, kedro_mlflow/pipeline/pipeline_ml.py, tests/framework/hooks/test_pipeline_hook.py
I have changed my mind: #59 is much trickier than it seems because of the need to import `get_mlflow_config` inside the hook which has a lot of side effects. For the sake of clarity, let's merge only the fix for #58 first. I'll open a separated PR for #59.
=> FIX #58 - Move MlflowPipelineHook args to PipelineML class

kedro_mlflow/framework/cli/cli.py, tests/framework/cli/test_cli.py
Fix this bug which is annoying with a false warning (even if the function call was ok)
=> FIX  #14 - Remove unintended warning message when calling 'kedro mlfow init' command

CHANGELOG.md, README.md, docs/source/01_introduction/02_motivation.md, docs/source/02_hello_world_example/02_first_steps.md, docs/source/03_tutorial/05_version_datasets.md, docs/source/05_python_objects/01_DataSets.md, kedro_mlflow/io/__init__.py, kedro_mlflow/io/mlflow_dataset.py, tests/io/test_mlflow_dataset.py
Apart from doc updates, I've added a `DeprecationWarning` and kept the old `MlflowDataSet` class. 
We will removed it entirely in 0.4.0.
=> Fix #63 - Deprecate 'MlflowDataSet' and rename it 'MlflowArtifactDataSet'

kedro_mlflow/framework/hooks/node_hook.py
Fix the issue #81.
Remove the lines from the constructor
- *N/A* Update the documentation to reflect the code changes
- *N/A* Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- *N/A* Add tests to cover your changes
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am …
=> FIX #81 - Remove deprecated arguments from MlflowNodeHook constructor

CHANGELOG.md, kedro_mlflow/pipeline/pipeline_ml.py, tests/pipeline/test_pipeline_ml.py
FIX #83 - Check input_name when set in PipelineML
- Decorate `input_name` with `@property`
- Ensure 100% test coverage for `pipeline_ml`
- *N/A* Update the documentation to reflect the code changes
=> FIX #83 - Check input_name when set in PipelineML

CHANGELOG.md, README.md, docs/source/01_introduction/02_motivation.md, docs/source/05_python_objects/03_Pipelines.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/pipeline/__init__.py, kedro_mlflow/pipeline/pipeline_ml.py, kedro_mlflow/pipeline/pipeline_ml_factory.py, requirements/requirements.txt, tests/framework/hooks/test_pipeline_hook.py, tests/mlflow/test_kedro_pipeline_model.py, tests/pipeline/test_pipeline_ml.py
Deprecate the confusing name of `pipeline_ml` function.
- Renamed `pipeline_ml` as `pipeline_ml_factory` everywhere (code, tests, docs)
- Add a deprecation warning to `pipeline_ml`
=> FIX #85 - Rename pipeline_ml as pipeline_ml_factory

CHANGELOG.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/context/mlflow_context.py, kedro_mlflow/framework/hooks/node_hook.py, kedro_mlflow/framework/hooks/pipeline_hook.py, tests/conftest.py, tests/framework/context/test_mlflow_context.py, tests/framework/hooks/test_node_hook.py, tests/framework/hooks/test_pipeline_hook.py
closes #66  #30 #72
This PR intend to fix mlflow configs related issues.
Some important changes :
* kedro-mlflow can now access to project context properties. That decouple the plugin from the template.
We used this access to change get_mlflow_config signature, the test have been updated accordignately.
* I add a .kedro.yml file, src folder and run.py file to the kedro project fixture for tests running in kedro 0.16.5
For more details, see changes.
Checklist
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my …
=> FIX #66 - accessing project context

.pre-commit-config.yaml, CHANGELOG.md, docs/source/05_python_objects/02_Hooks.md, docs/source/05_python_objects/03_Pipelines.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/pipeline/pipeline_ml.py, kedro_mlflow/pipeline/pipeline_ml_factory.py, requirements/test_requirements.txt, tests/framework/hooks/test_pipeline_hook.py, tests/pipeline/test_pipeline_ml.py
This PR close #70 and #106.
- Update the requirements to upgrade isort
- Update the pre-commit with isort
- New isortversion modfies a lot of docstring in the codebase
- Add missing links in the changelog
- Add a `model_signature` argument in `PipelineML` and `pipeline_ml_factory` whichenable the user to:
- infer automatically the schema of the input when logging in mlflow (default)
- do nothing
- pass a custom made schema for validating both the input and the output 
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not …
=> FIX #70 - Enforce input schema when logging a PipelineML

CHANGELOG.md, kedro_mlflow/io/__init__.py, kedro_mlflow/io/mlflow_dataset.py, kedro_mlflow/pipeline/__init__.py, kedro_mlflow/pipeline/pipeline_ml_factory.py, tests/io/test_mlflow_dataset.py, tests/pipeline/test_pipeline_ml.py
Close #105 by removing deprecated pipeline_ml and MlflowDataSet
- remove tests, import and definitions of these functions
=> FIX #105 - Remove deprecated pipeline_ml and MlflowDataSet

docs/source/03_tutorial/00_migration_guide.md, docs/source/03_tutorial/index.rst
Fix missing index update in #113 which prevents the migration guide to appear in documentation
- Add the `00_migration_guide.md` to `index.rst`
- NA Open this PR as a 'Draft Pull Request' if it is work-in-progress
- NA Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- NA Add tests to cover your changes
- I certify that (a) this …
=> PARTIAL #6 - Add migration guide to sphinx index

CHANGELOG.md, docs/source/04_experimentation_tracking/01_configuration.md, kedro_mlflow/framework/context/config.py, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/template/project/mlflow.yml, tests/framework/context/test_config.py, tests/framework/context/test_mlflow_context.py, tests/template/project/test_mlflow_yml.py
Fix #31 and #97.
- When instantiating a KedroMlflowConfig object, there is no interaction with mlflow to create the associated experiment. It must be created explicitly
-  A method was added to export mlflow credentials on the fly when running a pipeline.
```yaml
my_credentials: 
AWS_SECRET_KEY: <key>
```
```yaml
credentials: my_credentials
```
- interactively, you must now call the setup method to setus the configuration up:
```python
from kedro.context import load_context
from kedro_mlflow.context import get_mlflow_config
context=load_context(".")
mlflow_config=get_mlflow_config(context)
mlflow_config.setup(context)
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of …
=> Create KedroMlflowConfig.setup() method and enable configuration to export credentials as environment variables

CHANGELOG.md, kedro_mlflow/framework/hooks/pipeline_hook.py, tests/framework/hooks/test_pipeline_hook.py
Fix #121
Add the failed status when closing runs in the on_pipeline_error hook.
=> FIX #121 - Mark mlflow run as failed if kedro pipeline raises an error

.bumpversion.cfg
Fix wrong documentation reference in `bumpversion.cfg` which prevents the release candidate to be created.
Change link references in `bumpversion.cfg`
=> PARTIAL #6 - Fix documentation links in bumpversion configuration

CHANGELOG.md, docs/source/07_python_objects/03_Pipelines.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/mlflow/kedro_pipeline_model.py, kedro_mlflow/pipeline/pipeline_ml.py, kedro_mlflow/pipeline/pipeline_ml_factory.py, tests/framework/hooks/test_pipeline_hook.py, tests/mlflow/test_kedro_pipeline_model.py
Fix #133
- `KedroPipelineModel.load_context` now loads all the artifacts in MemoryDatasets
- It is possible to specify the copy_mode for each dataset in `KedroPipelineModel`, `PipelineML` and `pipeline_ml_factory` (either by specifying a string to make all the datasets have the same mode, or a dictionary to eventually specify different `copy_mode` for each dataset).
- It is possible to specify the Kedro `AbstractRunner` in `KedroPipelineModel`, `PipelineML` and `pipeline_ml_factory`
- I certify that (a) this contribution is my original creation and / or (b) to the …
=> FIX #133 - Enable to specify runner and copy_mode for KedroPipelineModel.predict to decrease inference time

CHANGELOG.md, docs/source/02_installation/02_setup.md, docs/source/03_getting_started/02_first_steps.md, docs/source/07_python_objects/04_CLI.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/context/mlflow_context.py, kedro_mlflow/utils.py, tests/framework/cli/test_cli.py, tests/framework/context/test_mlflow_context.py, tests/test_utils.py
Fix #159 
- Remove dynamic apparition of project CLI commands. They are now always displayed even if the project is not initialised yet.
- Remove `_aready_updated` function which is no longer used, since no check is made to verify that the projec tis initialized
- Add a `env` argument to `kedro mlflow init` to enable to create the configuration in another ocation than "base"
- Remove the possibility to call `kedro mlflow ui` outside of the project (this is not a breaking change: this code was not usable until now since the command did not display outside of a project)
- Add an extra check in `get_mlflow_config` to inform the user if the project is not initialised yet.
- The `mlflow.yml` is now created by default in `conf/local` instead of `conf/base`
- I submit this contribution under the …
=> FIX #159 - Refactor CLI to make mlflow.yml read and write more flexible to different configuration logic

CHANGELOG.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/pipeline/pipeline_ml.py, tests/framework/hooks/test_pipeline_hook.py, tests/io/models/test_mlflow_model_logger_dataset.py, tests/io/models/test_mlflow_model_saver_dataset.py, tests/mlflow/test_kedro_pipeline_model.py, tests/pipeline/test_pipeline_ml.py
Fix #158
- Update the ``extract_pipeline_artifacts`` function to automatically persist parameters
- Update the ``mlflow_pipeline_hook`` to create a TemporaryFolder on the fly when logging the pipeline as a Mlflow Model
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property …
=> FIX #158 - Autopickle input parameters  of inference pipeline in PipelineML

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/publish.yml, .github/workflows/test.yml, CONTRIBUTING.md, README.md, docs/source/02_installation/01_installation.md
The current workflow is unecessarily complex, having a single branch as source of truth will make deployment easier.
- Switch default branch from develop to master
- Update documentation accordingly
- Remove develop branch
- N/A Add a description of this change and add your name to the list of supporting contributions in the [`CHANGELOG.md`](https://github.com/Galileo-Galilei/kedro-mlflow/blob/develop/CHANGELOG.md) file. Please respect [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) guidelines.
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my …
=> FIX #57 - Change default branch from develop to master and simplify publishing workflow

.github/workflows/publish.yml
Fix a bug: publishing workflow was triggered on each merge instead of manually, due to the change of default branch
- Update the publish workflow to trigger it manually
=> FIX #57 - Trigger the publish action manually

CHANGELOG.md, kedro_mlflow/framework/cli/cli.py, requirements.txt, tests/conftest.py, tests/framework/cli/test_cli.py, tests/framework/context/test_config.py, tests/framework/context/test_mlflow_context.py, tests/framework/hooks/test_node_hook.py, tests/framework/hooks/test_pipeline_hook.py
Continue fixing #144 because current PyPI version does not work with kedro>=0.17.1
- Update all tests
- Update CLI to call ``configure_project`` command
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual …
=> FIX #144 - Make kedro-mlflow fully compatible with kedro>=0.17.1

CHANGELOG.md, docs/source/04_experimentation_tracking/01_configuration.md, kedro_mlflow/framework/cli/cli_utils.py, kedro_mlflow/framework/context/config.py, kedro_mlflow/framework/hooks/node_hook.py, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/framework/hooks/utils.py, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, kedro_mlflow/io/catalog/switch_catalog_logging.py, kedro_mlflow/io/metrics/mlflow_metrics_dataset.py, kedro_mlflow/io/models/mlflow_abstract_model_dataset.py, kedro_mlflow/io/models/mlflow_model_logger_dataset.py, kedro_mlflow/template/project/mlflow.yml, tests/framework/context/test_config.py, tests/framework/context/test_mlflow_context.py, tests/framework/hooks/test_all_hooks.py, tests/framework/hooks/test_pipeline_hook.py, tests/io/artifacts/test_mlflow_artifact_dataset.py, tests/io/metrics/test_mlflow_metrics_dataset.py, tests/io/models/test_mlflow_model_logger_dataset.py, tests/template/project/test_mlflow_yml.py
Implement partially #92 by adding the possibility to deactivate mlflow tracking in the configuration file.
=> Add possibility to deactivate mlflow tracking for given pipelines

CHANGELOG.md, docs/source/04_experimentation_tracking/01_configuration.md, docs/source/07_python_objects/04_CLI.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/context/config.py, kedro_mlflow/template/project/mlflow.yml, tests/framework/cli/test_cli.py
Fix #187 
- Change default port and host configuration to match mlflow's ones (in the `mlflow.yml` template and in `KedroMlflowConfig`)
- Pass `host` and `port` to when calling `mlflow ui` inside `kedro mlflow ui`
- Add `host` and `port` arguments to `ui`  to enable to overwrite these parameters at runtime
- I certify that the use of this …
=> FIX #187 - Pass host and port parameters from the configuration to the ui command and enable runtime overwriting

CHANGELOG.md, setup.py
Fix #193 
Remove the global group of commands in the setup.py, because ``kedro==0.17.3`` is bugged and no longer supports having both global and project commands.
=> FIX #193 - Remove global commands to make project CLI commands available again

docs/source/01_introduction/01_introduction.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/context/config.py, tests/framework/cli/test_cli.py, tests/framework/context/test_config.py, tests/framework/context/test_mlflow_context.py, tests/framework/hooks/test_all_hooks.py, tests/framework/hooks/test_node_hook.py, tests/framework/hooks/test_pipeline_hook.py
Tests were failing with kedro==0.17.3 due to new pipeline import system
- update hooks and pipeline tests
- enable KedroMlflowConfig.setup method to take a session as an argument instead of fetching the active one.
- I certify …
=> Migration/test to 0.17.3

.pre-commit-config.yaml, docs/source/05_framework_ml/03_framework_solutions.md, docs/source/05_framework_ml/04_example_project.md, docs/source/07_python_objects/01_DataSets.md, docs/source/07_python_objects/03_Pipelines.md, setup.py, tests/framework/hooks/test_pipeline_hook.py, tests/io/models/test_mlflow_model_logger_dataset.py, tests/io/models/test_mlflow_model_saver_dataset.py, tests/mlflow/test_kedro_pipeline_model.py
Tests were failing because most recent versions of mlflow expect a "dependencies" in conda.yml
- Update all tests and docs to ensure conda.yml are built with a "dependencies" key
- Update dependencies
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone …
=> Make test pass with mlflow>=1.19.0 with new conda env parser

CHANGELOG.md, docs/source/04_experimentation_tracking/03_version_datasets.md, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #95 
- Update the ``MlflowArtifactDataset.load()`` method to download the data from the run_id if it is specified instead of using the local filepath.
=> Enable to load data from an existing run_id with MlflowArtifactDataset (#95)

CHANGELOG.md, kedro_mlflow/framework/hooks/node_hook.py, kedro_mlflow/framework/hooks/utils.py, tests/framework/hooks/test_node_hook.py, tests/framework/hooks/test_utils.py
Close #224 
- Update the ``flatten_dict`` function to avoid an error when dictionnary keys are integer (concatenation with a string raise a TypeError)
=> Fix error when logging a dictionnary parameters with integer keys (#224)

CHANGELOG.md, docs/source/04_experimentation_tracking/05_version_metrics.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/io/metrics/__init__.py, kedro_mlflow/io/metrics/mlflow_abstract_metric_dataset.py, kedro_mlflow/io/metrics/mlflow_metric_dataset.py, kedro_mlflow/io/metrics/mlflow_metric_history_dataset.py, kedro_mlflow/io/metrics/mlflow_metrics_dataset.py, requirements.txt, tests/framework/hooks/test_all_hooks.py, tests/framework/hooks/test_pipeline_hook.py, tests/io/metrics/test_mlflow_metric_dataset.py, tests/io/metrics/test_mlflow_metric_history_dataset.py, tests/io/metrics/test_mlflow_metrics_dataset.py
=> Refactor MlflowMetricsDataSet for a better user experience

.github/workflows/test.yml, README.md, docs/conf.py, docs/source/04_experimentation_tracking/02_version_parameters.md, docs/source/04_experimentation_tracking/05_version_metrics.md, docs/source/07_python_objects/01_DataSets.md
Fix typo in documentation for the new AbstractMetricDataSet + render ``eval_rst`` block with Autostructify in sphinx
NA
- I certify that (a) this contribution is my original creation and / …
=> Fix typo for new MetricDataSet and eval_rst rendering

.pre-commit-config.yaml, CHANGELOG.md, docs/conf.py, docs/index.rst, docs/source/08_API/kedro_mlflow.config.rst, docs/source/08_API/kedro_mlflow.extras.extensions.rst, docs/source/08_API/kedro_mlflow.framework.cli.rst, docs/source/08_API/kedro_mlflow.framework.hooks.rst, docs/source/08_API/kedro_mlflow.io.rst, docs/source/08_API/kedro_mlflow.mlflow.rst, docs/source/08_API/kedro_mlflow.pipeline.rst, docs/source/08_API/kedro_mlflow.rst, docs/source/08_advanced_use/01_run_with_mlproject.md, docs/source/08_advanced_use/02_compatbility_chart.md, docs/source/08_advanced_use/index.rst, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, kedro_mlflow/utils.py, setup.py
Add support for #110
- Create an "API Documentation" folder in the docs, and use autodoc to document it.
- Note that many method are not properly documetned with docstrings yet, so I do not get rid of the 
07_Python_objects section yet.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the …
=> :memo: Use sphinx to automatically document the API with docstrings

.github/workflows/test.yml, CHANGELOG.md, docs/source/05_framework_ml/03_framework_solutions.md, docs/source/05_pipeline_serving/01_mlflow_models.md, docs/source/05_pipeline_serving/02_custom_kedro_pipeline_model.md, docs/source/05_pipeline_serving/index.rst, docs/source/07_python_objects/03_Pipelines.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/mlflow/kedro_pipeline_model.py, kedro_mlflow/pipeline/__init__.py, kedro_mlflow/pipeline/pipeline_ml.py, tests/io/models/test_mlflow_model_logger_dataset.py, tests/io/models/test_mlflow_model_saver_dataset.py, tests/mlflow/test_kedro_pipeline_model.py, tests/pipeline/test_pipeline_ml.py
=> Make the KedroPipelineModel custom mlflow model able to serve a Pipeline instead of only PipelineML

CHANGELOG.md, docs/source/05_framework_ml/03_framework_solutions.md, docs/source/05_framework_ml/04_example_project.md, docs/source/07_python_objects/01_DataSets.md, docs/source/07_python_objects/03_Pipelines.md, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/pipeline/pipeline_ml.py, kedro_mlflow/pipeline/pipeline_ml_factory.py, tests/framework/hooks/test_pipeline_hook.py, tests/pipeline/test_pipeline_ml.py
=> :sparkles: :boom: Change PipelineML signature to pass kwargs to mlflow.pyfunc.log_model and KedroPipelineModel

CHANGELOG.md, README.md, docs/source/02_installation/03_migration_guide.md, docs/source/04_experimentation_tracking/01_configuration.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/extras/extensions/ipython.py, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/framework/hooks/node_hook.py, kedro_mlflow/framework/hooks/pipeline_hook.py, kedro_mlflow/framework/hooks/utils.py, kedro_mlflow/template/project/mlflow.yml, tests/config/test_get_mlflow_config.py, tests/config/test_kedro_mlflow_config.py, tests/framework/cli/test_cli.py, tests/framework/hooks/test_all_hooks.py, tests/framework/hooks/test_node_hook.py, tests/framework/hooks/test_pipeline_hook.py, tests/template/project/test_mlflow_yml.py
Close #77
The config entries are renamed for readibility and consistency with the mlflow API. 
The mlflow.yml now looks like this: 
```yaml
server:
mlflow_tracking_uri: mlruns
stores_environment_variables: {}
credentials: null
tracking:
disable_tracking:
pipelines: []
experiment:
name: {{ python_package }}
restore_if_deleted: True
run:
id: null 
name: null 
nested: True 
params:
dict_params:
flatten: False
recursive: True
sep: "." 
long_params_strategy: fail 
ui:
port: "5000" # the port to use for the ui. Use mlflow default with 5000.
host: "127.0.0.1"  # the host to use for the ui. Use mlflow efault of "127.0.0.1".
```
- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, …
=> :recycle: Refactor mlflow configuration to match mlflow API

kedro_mlflow/framework/cli/cli.py, tests/framework/cli/test_cli_modelify.py, tests/template/project/test_mlflow_yml.py
Close #282. Persisting paramters in the ``modelify`` command is consistent with ``pipeline_ml_factory`` and ``after_pipeline_run`` hook
- persists parameters in modelify command in the same way we do for ``after_pipeline_run`` hook.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the …
=> Automatically persist parameters in modelify command (#282)

CHANGELOG.md, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #258
- I've modified the construction of the local path (either for save or load) to look for a ``_path`` attribute if ``_filepath`` does not exist
=> :bug: Make MlflowArtifactDataSet work with kedro.io.PartitionedDataSet

.github/workflows/prepare-release.yml
Avoid operational errors when typing the part of the version to update when releasing the package
Use the new feature in github action which enable specifying the list of choices in a workflow_dispatch](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/) to define the part of the version to bump
- I submit …
=> :construction_worker: Make user choose the part of the version to update in a dropdown list during release (#57)

CHANGELOG.md, kedro_mlflow/pipeline/pipeline_ml.py, tests/framework/hooks/test_hook_pipeline_ml.py, tests/io/models/test_mlflow_model_logger_dataset.py
Close #329
- pass ``kpm_kwargs`` and ``log_model_kwargs`` to ``_turn_pipeline_to_ml`` method of ``PipelineML``
- refactor merge with default for readibility
=> :bug: Correctly pass kpm_kwargs and log_model_kwargs to pipeline_ml_factory instead of always using default values (#329)

CHANGELOG.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/config/test_kedro_mlflow_config.py, tests/framework/cli/test_cli.py
Close #314
- KedroMlflowConfig no longer takes ``project path`` at instantiation, instead it is retrieved from context in ``KedroMlflowConfig.setup()``
- no error is raised if the config is instantiated outisde of a kedro project
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual …
=> Refactor KedroMlflowConfig to avoid dependency on project_path at instantiation

CHANGELOG.md, kedro_mlflow/framework/cli/cli.py
=> :bug: Stop logging a success init message when init fails (#336)

.pre-commit-config.yaml, CHANGELOG.md, docs/source/02_installation/02_setup.md, docs/source/02_installation/03_migration_guide.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/config/test_get_mlflow_config.py
Close #328
Change after_context_created hook to use default configuration instead of raising an error when no mlflow.yml file exists.
=> :sparkles: Enable running pipeline without mlflow.yml file (#328)

CHANGELOG.md, kedro_mlflow/__init__.py, kedro_mlflow/mlflow/kedro_pipeline_model.py, tests/framework/cli/test_cli_modelify.py
Close #348 
Set the logging level in the root ``__init__.py`` so it is set globally. 
=> Set logging level

CHANGELOG.md, docs/source/01_introduction/01_introduction.md, docs/source/02_installation/02_setup.md, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/config/test_get_mlflow_config.py, tests/framework/hooks/test_hook_log_parameters.py
Fix an inconsistency behaviour when between mlflow.yml file was all commented out (use "Default"experiment name) and when the conf was missing (use project name as experiment name)
Change setup to manage a missing key in tracking.experiment.name
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate …
=> :bug: Use project_name as default experiment_name even if it is not specified in mlflow.yml (#328)

CHANGELOG.md, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #362
Update MlflowArtifactDataset.load to use Path() object instead of str.
=> :bug: Correctly loads the artifact when both artifact_path and run_id are specified in MlflowArtifactDataSet (#362)

CHANGELOG.md, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #362
Do not specify fodler for download_artifacts, but download in temp folder and then copy to the right destination. 
=> :bug: Force downloading locally artifacts from a run_id af ignore to specified filepath (#362)

CHANGELOG.md, docs/source/04_experimentation_tracking/01_configuration.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/template/project/mlflow.yml, tests/config/test_get_mlflow_config.py, tests/config/test_kedro_mlflow_config.py
First step for #260
- add an ``mlflow_registry_uri`` key in ``KedroMlflowConfig`` and ``mlflow.yml``
=> Add the ability to configure mlflow_registry_uri in mlflow.yml (#260)

CHANGELOG.md, docs/source/03_getting_started/01_example_project.md, docs/source/04_experimentation_tracking/01_configuration.md, docs/source/06_interactive_use/01_notebook_use.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/template/project/mlflow.yml, tests/config/test_get_mlflow_config.py, tests/config/test_kedro_mlflow_config.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #357
- add an extra key in ``mlflow.yml`` and ``KedroMlflwoConfig`` to specifuy a path to custom class which inherits from ``mlflow.tracking.request_header.abstract_request_header_provider.RequestHeaderProvider``
- automatically resolve and add this class to the mlflow private global ``mlflow.tracking.request_header.registry._request_header_provider_registry``
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) …
=> :sparkles: Add custom request_header_provider support for authorization with expiring tokens

CHANGELOG.md, docs/source/04_experimentation_tracking/01_configuration.md, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/framework/hooks/test_hook_active_run.py
Close #358, prepare #11 and support https://github.com/getindata/kedro-azureml/issues/9
- 
=> Enable using an active run in kedro-mlflow

.pre-commit-config.yaml, CHANGELOG.md, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/framework/hooks/test_run_name.py
Fix #392
If pipeline_name is None in the hook, use __default instead
=> :bug: Use '__default__' as the mlflow run name when the pipeline is not specified in 'kedro run' command

CHANGELOG.md, docs/source/07_python_objects/01_DataSets.md, docs/source/08_API/kedro_mlflow.io.rst, kedro_mlflow/io/models/__init__.py, kedro_mlflow/io/models/mlflow_model_registry_dataset.py, tests/io/models/test_mlflow_model_registry_dataset.py
Add a MlflowModelRegistryDataSet to load a model directly from the mlflow model registry (#260)
Close #260 
Add MlflowModelRegistryDataSet class and its load method.  
=> :sparkles: Add a MlflowModelRegistryDataSet

CHANGELOG.md, docs/source/05_pipeline_serving/03_cli_modelify.md, docs/source/07_python_objects/04_CLI.md, kedro_mlflow/framework/cli/cli.py, tests/framework/cli/test_cli_modelify.py
Close #408 
- update documentation for the ``modelify`` command
- add run name argument 
=> Add a run_name argument in mlflow modelify command and use 'modelify' as default

CHANGELOG.md, kedro_mlflow/framework/hooks/mlflow_hook.py
=> add except, update changelog

CHANGELOG.md, README.md, docs/source/01_introduction/02_motivation.md, docs/source/02_installation/03_migration_guide.md, docs/source/03_getting_started/02_first_steps.md, docs/source/04_experimentation_tracking/03_version_datasets.md, docs/source/04_experimentation_tracking/04_version_models.md, docs/source/04_experimentation_tracking/05_version_metrics.md, docs/source/06_interactive_use/01_notebook_use.md, docs/source/07_python_objects/01_DataSets.md, kedro_mlflow/framework/hooks/mlflow_hook.py, kedro_mlflow/io/artifacts/__init__.py, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, kedro_mlflow/io/metrics/__init__.py, kedro_mlflow/io/metrics/mlflow_abstract_metric_dataset.py, kedro_mlflow/io/metrics/mlflow_metric_dataset.py, kedro_mlflow/io/metrics/mlflow_metric_history_dataset.py, kedro_mlflow/io/metrics/mlflow_metrics_dataset.py, kedro_mlflow/io/models/__init__.py, kedro_mlflow/io/models/mlflow_abstract_model_dataset.py, kedro_mlflow/io/models/mlflow_model_logger_dataset.py, kedro_mlflow/io/models/mlflow_model_registry_dataset.py, kedro_mlflow/io/models/mlflow_model_saver_dataset.py, tests/framework/hooks/test_hook_deactivate_tracking.py, tests/framework/hooks/test_hook_log_metrics.py, tests/io/artifacts/test_mlflow_artifact_dataset.py, tests/io/metrics/test_mlflow_metric_dataset.py, tests/io/metrics/test_mlflow_metric_history_dataset.py, tests/io/metrics/test_mlflow_metrics_dataset.py, tests/io/models/test_mlflow_model_registry_dataset.py
=> Changing DataSet to Dataset#391

docs/source/03_getting_started/02_first_steps.md, docs/source/04_experimentation_tracking/03_version_datasets.md, docs/source/05_pipeline_serving/04_hook_pipeline_ml.md, docs/source/07_python_objects/01_DataSets.md, kedro_mlflow/mlflow/kedro_pipeline_model.py, requirements.txt, setup.py, tests/framework/cli/test_cli_modelify.py, tests/framework/hooks/test_hook_deactivate_tracking.py, tests/framework/hooks/test_hook_log_metrics.py, tests/framework/hooks/test_hook_pipeline_ml.py, tests/io/artifacts/test_mlflow_artifact_dataset.py, tests/io/models/test_mlflow_model_logger_dataset.py, tests/io/models/test_mlflow_model_saver_dataset.py, tests/mlflow/test_kedro_pipeline_model.py, tests/pipeline/test_pipeline_ml.py
Prepare 0.19
- Imports  PickleDataset and CSVDataset from kedro_datasets
- Add ``kedro-datasets`` as a dependency
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am …
=> :recycle: Import from kedro_datasets instead of kedro.extras

CHANGELOG.md, docs/source/05_pipeline_serving/02_custom_kedro_pipeline_model.md, docs/source/07_python_objects/03_Pipelines.md, docs/source/07_python_objects/04_CLI.md, kedro_mlflow/mlflow/kedro_pipeline_model.py, tests/framework/hooks/test_hook_pipeline_ml.py
Close #463
- Set KedroPipelineModel default copy_mode to 'assign'
-  N/A Open this PR as a 'Draft Pull Request' if it is work-in-progress
=> :boom: :sparkles: Set KedroPipelineModel default copy_mode to 'assign' (#463)

CHANGELOG.md, README.md, docs/source/01_introduction/02_motivation.md, docs/source/02_installation/03_migration_guide.md, docs/source/03_getting_started/02_first_steps.md, docs/source/04_experimentation_tracking/03_version_datasets.md, docs/source/04_experimentation_tracking/04_version_models.md, docs/source/04_experimentation_tracking/05_version_metrics.md, docs/source/07_python_objects/01_DataSets.md, kedro_mlflow/framework/hooks/mlflow_hook.py, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, kedro_mlflow/io/catalog/switch_catalog_logging.py, kedro_mlflow/io/metrics/__init__.py, kedro_mlflow/io/metrics/mlflow_abstract_metric_dataset.py, kedro_mlflow/io/metrics/mlflow_metrics_dataset.py, kedro_mlflow/mlflow/kedro_pipeline_model.py, tests/conftest.py, tests/framework/cli/test_cli.py, tests/framework/cli/test_cli_modelify.py, tests/framework/hooks/test_hook_deactivate_tracking.py, tests/framework/hooks/test_hook_log_metrics.py, tests/framework/hooks/test_hook_log_parameters.py, tests/framework/hooks/test_hook_pipeline_ml.py, tests/io/artifacts/test_mlflow_artifact_dataset.py, tests/io/metrics/test_mlflow_metrics_dataset.py, tests/io/models/test_mlflow_model_local_filesystem_dataset.py, tests/io/models/test_mlflow_model_tracking_dataset.py, tests/mlflow/test_kedro_pipeline_model.py
Prepare kedro 0.19 release
- fix failing tests due to cookiecutter hooks
- :boom: rename all ``data_set`` entries int eh code by ``dataset``. This changes the signature of ``MLflowArtifactDataSet``.
- Refactor tests to remove logging monkeypatching. this makes tests simpler. 
Notice that tests do not pass because we are on the latest 0.18.x version, but they dont pass either on the develop branch because of following issues: https://github.com/kedro-org/kedro/issues/3214
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is …
=> Refactor codes and tests to match kedro==0.19 conventions

.pre-commit-config.yaml, CHANGELOG.md, kedro_mlflow/framework/hooks/mlflow_hook.py, requirements.txt, setup.py, tests/config/test_get_mlflow_config.py
=> :sparkles: :arrow_up: Make kedro-mlflow compatible with pydantic v2 (#476)

.gitignore, tests/conftest.py, tests/io/artifacts/test_mlflow_artifact_dataset.py, tests/io/metrics/test_mlflow_metrics_dataset.py, tests/io/models/test_mlflow_model_tracking_dataset.py
Close #475
Lots of experimentation: 
- I can't increase tests speeds, because the only thing (by a vast margin) that is really slow is the ``log_model`` function in mlflow. 
- I tried to avoid runnnigs tests creatings a bunch of mlruns folder, especially at the root of the projects. The solution was to change the fixture which cleanup after each tets, because a "gloabl" variable created in mlflow was the root cause of everything. See comment here : https://github.com/Galileo-Galilei/kedro-mlflow/pull/478/files#diff-e52e4ddd58b7ef887ab03c04116e676f6280b824ab7469d5d3080e5cba4f2128R37-R44
I also move some fixture (``tracking_uri`` & ``mlflow_client`` to ``conftest.py`` to remove duplicated code. 
- I submit this contribution under the [Apache 2.0 …
=> Prevent tests from creating mlruns folder in several places (#475)

CHANGELOG.md, kedro_mlflow/framework/hooks/mlflow_hook.py, tests/framework/hooks/test_hook_pipeline_ml.py
This PR fixes the problem with PipelineML not recognizing catalogue entities with dataset factory patterns.
The `after_pipeline_run` was updated to run `catalog.exists` for all pipeline datasets, as suggested by @Galileo-Galilei 
A unit test was added for the case when a DataCatalog has data factory patterns.
- I certify that the use of this …
=> :bug: Materialize dataset factories before instantiating KedroPipelineModel

CHANGELOG.md, kedro_mlflow/framework/cli/cli.py, kedro_mlflow/utils.py, requirements.txt, tests/framework/cli/test_cli.py, tests/framework/cli/test_cli_modelify.py
- Fix a bug which prevents importng the CLi with kedro==0.19.4 because I relied on private ``_is_project``.
- On the way, make all project level CLI (``init``, ``ui``, and ``modelify``) work inside a subdirectory and not only at the root of kedro level
- Create my own ``_is_project`` and ``_find_kedro_project`` functions which manges the import of the private functions of kedro.
- Change all CLI to get the project path with ``_find_kedro_project`` instead of taking ``Path.cwd``. 
- I certify that (a) this …
=> Make project level cli work inside subdirectory (#531)

.github/workflows/publish.yml
Use OIDC to connect to PyPI when releasing for more security, and update actions with more reputed ones or newer versions
Use publish.yml from kedro-pandera updated recently.
=> :closed_lock_with_key: Use OIDC to authentify with PYPI and update dependencies versions

CHANGELOG.md, kedro_mlflow/pipeline/pipeline_ml.py, tests/pipeline/test_pipeline_ml.py
Close #569
- Add ``only_nodes_with_namespace`` and ``__sub__`` methods for ``PipelineML`` object
- I have tested manually but kedro-viz 9.2.0 does not fail with a simple PipelineML in spaceflights-pandas. I need 
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights …
=> Allow only_nodes_with_namespace in PipelineML for kedro-viz compatibility

kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py, tests/framework/cli/test_cli_modelify.py, tests/io/artifacts/test_mlflow_artifact_dataset.py
Close #592
add a return statement on MLflowArtifactDataset._load for old style dataset
=> :bug: Force return on load for old style datasets (#592)

CHANGELOG.md, kedro_mlflow/io/metrics/mlflow_metrics_history_dataset.py
=> :bug: Replace get_all_metrics in MLflowMetricsHistoryDataset to be compatible with all Mlflow stores (#582)

CHANGELOG.md, kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py
=> :bug: :ambulance: Make MlflowArtifactDataset load and save compatible with modern datasets without private _load and _save (#598)

kedro_mlflow/pipeline/pipeline_ml.py, tests/pipeline/test_pipeline_ml.py
Implements the rest of PipelineML slicing functionalities. 
Currently, when something fails while running a pipeline, kedro tries to provide a hint command to resume. However, as PipelineML doesn't implement them all, it throws an additional error while trying to provide a hint. This results in messy logging on the actual error (you need to scroll up to see what actually broke), and oftentimes one can mistakenly think that something went wrong during packaging of the model.
This PR tries to fix this problem.
- I certify that (a) this contribution is my original …
=> Implement missing PipelineML slicing functionalities

CHANGELOG.md, kedro_mlflow/io/models/mlflow_model_registry_dataset.py, tests/framework/cli/test_cli_modelify.py, tests/io/models/test_mlflow_model_registry_dataset.py
=> :loud_sound: Log model version information when a model is loaded from the registry (#552)

docs/source/02_installation/02_setup.md, pyproject.toml
Fix build https://github.com/Galileo-Galilei/kedro-mlflow/actions/runs/13020609952/job/36320216122
Fix reference to 03_gettingstarted to 03_quickstart
=> :memo: :construction_worker: Fix documentation reference to quickstart

.github/workflows/prepare-release.yml, .github/workflows/publish.yml, .github/workflows/test.yml, CHANGELOG.md, requirements.txt, setup.py
Improve github actions speed with uv instead of pip and pytest-xdist to parallelize test. 
- Modify all github action sto setup uv and then use "uv run" and "uv pip" everywhere
- use "-n auto" option when running pytest in the CI
The CI time has improved from [8'52''](https://github.com/Galileo-Galilei/kedro-mlflow/actions/runs/13020907537) to [3' 37''](https://github.com/Galileo-Galilei/kedro-mlflow/actions/runs/13219115337)
- NA Add tests to cover …
=> :construction_worker: :zap: Improve github actions speed with uv and pytest-xdist

.gitignore, CHANGELOG.md, README.md, kedro_mlflow/io/catalog/add_run_id_to_artifact_datasets.py, tests/framework/hooks/test_hook_log_artifact.py
Close #622 
Add a check to specify update run id beteen thread only if it is not set by user. 
- [] Update the documentation to reflect the code changes
=> Load from a specific run_id for MlflowArtifactDataset

CHANGELOG.md, kedro_mlflow/config/kedro_mlflow_config.py, kedro_mlflow/template/project/mlflow.yml, tests/config/test_get_mlflow_config.py, tests/config/test_kedro_mlflow_config.py, tests/template/project/test_mlflow_yml.py
Close #610
- Add a configuration in ``mlflow.yml`` to disable autologging globally and set it to true by default. 
- Trigger it in ``KedroMlflowConfig.setup()``
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights …
=> :sparkles: Add configuration to disable autologging for Databricks

CHANGELOG.md, kedro_mlflow/io/models/mlflow_model_registry_dataset.py
Resolves #670 
* Added conditional check before logging `run_id` in `kedro_mlflow/io/models/mlflow_model_registry_dataset.py`
=> Fix `run_id` logging error while loading `MlflowModelRegistryDataset`
